CoffeeShop/Models/AboutUs.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CoffeeShop.Models
{
    public class AboutUs:Base
    {
       

        [Required]
        [MaxLength(200, ErrorMessage = "Simvol sayi 200-den cox ola bilmez.")]
        [MinLength(3)]
        //[Column("BASLIQ")]
        public string Title { get; set; }

        [Required]
        [MaxLength(400,ErrorMessage ="Simvol sayi 400-den cox ola bilmez.")]
        [MinLength(3)]
        public string UpTitle { get; set; }
    }
}

CoffeeShop/Models/Base.cs
using System.ComponentModel.DataAnnotations;

namespace CoffeeShop.Models
{
    public class Base
    {
        [Key]
        public int Id { get; set; }
    }
}

CoffeeShop/Models/ContactUs.cs
using System.ComponentModel.DataAnnotations;

namespace CoffeeShop.Models
{
    public class ContactUs:Base
    {
       

        [Required]
        [MaxLength(50,ErrorMessage ="Name 50 simvoldan cox ola bilmez.")]
        public string Name { get; set; }

        [Required]
        [MaxLength(75, ErrorMessage = "Email 75 simvoldan cox ola bilmez.")]
        public string Email { get; set; }

        [Required]
        [MaxLength(30, ErrorMessage = "Number 30 simvoldan cox ola bilmez.")]
        public int Number { get; set; }

        [Required]
        [MaxLength(500, ErrorMessage = "Message 1000 simvoldan cox ola bilmez.")]
        public string Message { get; set; }
    }
}

CoffeeShop/Models/Gallery.cs
using System.ComponentModel.DataAnnotations;

namespace CoffeeShop.Models
{
    public class Gallery:Base
    {
        

        [Required]
        public string Pictures { get; set; }



    }
}

CoffeeShop/Models/Services.cs
using System.ComponentModel.DataAnnotations;

namespace CoffeeShop.Models
{
    public class Services:Base
    {
         

        [Required]
        public string Icon { get; set; }

        [Required]
        [MaxLength(50,ErrorMessage ="Simvol sayi 50-den cox ola bilmez.")]
        public string Title { get; set; }

        [Required]
        [MaxLength(250, ErrorMessage = "Simvol sayi 250-den cox ola bilmez.")]
        public string UpTitle { get; set; }
    }
}

CoffeeShop/Controllers/AboutUsController.cs
using CoffeeShop.Models;
using CoffeeShop.Data;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly CoffeeShopDbContext _context;
        public AboutUsController(CoffeeShopDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            AboutUs? aboutUs = _context.AboutUs.FirstOrDefault();
            return View(aboutUs);
        }
    }
}

CoffeeShop/Controllers/ContactUsController.cs
using CoffeeShop.Models;
using CoffeeShop.Data;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class ContactUsController : Controller
    {
        private readonly CoffeeShopDbContext _context;
        public ContactUsController(CoffeeShopDbContext context)
        {
            _context=context;
        }
        public IActionResult Index()
        {
            ContactUs? contactUs = _context.ContactUs.FirstOrDefault();
            return View(contactUs);
        }
    }
}

CoffeeShop/Controllers/GalleryController.cs
using CoffeeShop.Models;
using CoffeeShop.Data;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class GalleryController : Controller
    {
        private readonly CoffeeShopDbContext _context;
        public GalleryController(CoffeeShopDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Gallery> gallery = _context.Gallery.ToList();
            return View(gallery);
        }
    }
}

CoffeeShop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoffeeShop/Controllers/ServicesController.cs
using CoffeeShop.Data;
using CoffeeShop.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeShop.Controllers
{
    public class ServicesController : Controller
    {
        private readonly CoffeeShopDbContext _context;
        public ServicesController(CoffeeShopDbContext context)
        {
            _context = context; 
        }
        public IActionResult Index()
        {
            List<Services> services = _context.Services.ToList();
            return View(services);
        }
    }
}

CoffeeShop/Views/AboutUs/Index.cshtml
@model AboutUs
<!-- about section start -->
<div class="about_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="about_taital_main">
                    <div class="about_taital">About Us</div>
                    <p class="about_text">@Model.Title</p>
                    <p class="about_text">@Model.UpTitle</p>
                    <div class="read_bt"><a href="#">Read More</a></div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="about_img"><img src="images/about-img.png"></div>
            </div>
        </div>
    </div>
</div>
<!-- about section end -->

CoffeeShop/Views/ContactUs/Index.cshtml
@model ContactUs

<!-- contact section start -->
<div class="contact_section layout_padding">
    <div class="container">
        <h1 class="contact_text">Contact Us</h1>
    </div>
</div>
<div class="contact_section_2 layout_padding">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 padding_0">
                <div class="mail_section">
                    <div class="email_text">
                        <div class="form-group">
                            <input type="text" class="email-bt" placeholder="@Model.Name" name="Email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="email-bt" placeholder="@Model.Email" name="Email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="email-bt" placeholder="@Model.Number" name="Email">
                        </div>
                        <div class="form-group">
                            <textarea class="massage-bt" placeholder="@Model.Message" rows="5" id="comment" name="Massage"></textarea>
                        </div>
                        <div class="send_btn">
                            <div type="text" class="main_bt"><a href="#">SEND</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 padding_0">
                <div class="map-responsive">
                    <iframe src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0s1a7phLN0iaD6-UE7m4qP-z21pH0eSc&q=Eiffel+Tower+Paris+France" width="600" height="508" frameborder="0" style="border:0; width: 100%;" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- contact section end -->

CoffeeShop/Views/Gallery/Index.cshtml
@model List<Gallery>
<!-- gallery section start -->
<div class="gallery_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="gallery_taital">Our Gallery</h1>
                <p class="gallery_text">Lorem Ipsum is simply dummy text of printing typesetting ststry lorem Ipsum the industry'ndard dummy text ever since of the 1500s, when an unknown printer took a galley of type and scra make a type specimen book. It has</p>
            </div>
        </div>
        <div class="">
            <div class="gallery_section_2">
                <div class="row">
                    @foreach(var image in Model)
                    {
                    <div class="col-md-4">
                        <div class="container_main">
                            <img src="images/@image.Pictures" alt="Avatar" class="image">
                            <div class="overlay">
                                <div class="text"><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></div>
                            </div>
                        </div>
                    </div>
                    }
                   
                </div>
            </div>
           
        </div>
        <div class="seemore_bt"><a href="#">See More</a></div>
    </div>
</div>
<!-- gallery section end -->

CoffeeShop/Views/Services/Index.cshtml
@model List<Services>
<!-- services section start -->
<div class="services_section layout_padding">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="services_taital">Services</h1>
                <p class="services_text">Typesetting industry lorem Ipsum is simply dummy text of the </p>
            </div>
        </div>
        <div class="services_section_2">
            <div class="row">
                @foreach(var services in Model)
                {
                <div class="col-lg-4 col-sm-12 col-md-4">
                    <div class="box_main active">
                        <div class="house_icon">
                            <img src="images/@services.Icon" class="image_1">
                            <img src="images/@services.Icon" class="image_2">
                        </div>
                        <h3 class="decorate_text">@services.Title</h3>
                        <p class="tation_text">@services.UpTitle</p>
                        <div class="readmore_bt"><a href="#">Read More</a></div>
                    </div>
                </div>
                }

                
              
            </div>
        </div>
    </div>
</div>
<!-- services section end -->

CoffeeShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Grand Coffee</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <!-- Responsive-->
    <link rel="stylesheet" href="css/responsive.css">
    <!-- fevicon -->
    <link rel="icon" href="images/fevicon.png" type="image/gif" />
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="css/jquery.mCustomScrollbar.min.css">
    <!-- Tweaks for older IEs-->
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
    <!-- owl stylesheets -->
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/owl.theme.default.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
</head>
<body>
    <!--header section start -->
    <div class="header_section">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="logo"><a href="index.html"><img src="images/logo.png"></a></div>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="AboutUs" asp-action="Index">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Gallery" asp-action="Index">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="ContactUs" asp-action="Index">Contact Us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
    <!--header section end -->
    @RenderBody();
    <!-- footer section start -->
    <div class="footer_section layout_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6">
                    <h3 class="useful_text">About</h3>
                    <p class="footer_text">consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation u</p>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h3 class="useful_text">Menu</h3>
                    <div class="footer_menu">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li><a href="about.html">About Us</a></li>
                            <li><a href="gallery.html">Gallery</a></li>
                            <li><a href="services.html">Services</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h1 class="useful_text">Useful Link</h1>
                    <p class="dummy_text">Adipiscing Elit, sed do Eiusmod Tempor incididunt </p>
                </div>
                <div class="col-lg-3 col-sm-6">
                    <h1 class="useful_text">Contact Us</h1>
                    <div class="location_text">
                        <ul>
                            <li>
                                <a href="#">
                                    <i class="fa fa-map-marker" aria-hidden="true"></i><span class="padding_left_10">Address : Loram Ipusm</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-phone" aria-hidden="true"></i><span class="padding_left_10">Call : +01 1234567890</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <i class="fa fa-envelope" aria-hidden="true"></i><span class="padding_left_10">Email : demo@gmail.com</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- footer section end -->
    <!-- copyright section start -->
    <div class="copyright_section">
        <div class="container">
            <p class="copyright_text">2020 All Rights Reserved. Design by <a href="https://html.design">Free html  Templates</a></p>
        </div>
    </div>
    <!-- copyright section end -->
    <!-- Javascript files-->
    <script src="js/jquery.min.js"></script>
    <script src="js/popper.min.js"></script>
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery-3.0.0.min.js"></script>
    <script src="js/plugin.js"></script>
    <!-- sidebar -->
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="js/custom.js"></script>
</body>
</html>